version: '3.1'

services:
  reverse-proxy:
        image: traefik:2.1
        restart: always
        ports:
          - "99:80"
          - "8080:8080"
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock
          - ./traefik.yml:/etc/traefik/traefik.yml:ro
        #networks:
        #    - traefik
        container_name: traefik

  web_traefik:
    build: 
          context: .
          dockerfile: Dockerfile
    volumes:
      - .:/var/www/html
    links:
      - db_traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.web_traefik.rule=Host(`46.226.107.16`)"
      - "traefik.http.routers.web_traefik.entrypoints=web"
      - "traefik.http.routers.web_traefik.service=web_traefik"
      - "traefik.http.services.web_traefik.loadbalancer.server.port=9680"
      - "traefik.http.routers.web_traefik.entrypoints=http"
  db_traefik:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: root
      MYSQL_USER: root
      MYSQL_PASSWORD: root